### ISSUE TITLE
Feature 7: User can add guests to Guest List Manager

### ISSUE THREAD

**Issue by michael5522** [michael5522/wedding-planner#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can both view and add guests on the Guest List Manager page
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will input person info and be view the whole list
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-10-13 at 8 49 34 PM](https://user-images.githubusercontent.com/55678486/195758338-261479e6-b7ad-4dc1-a043-9cc7405e03ba.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to add a new guest

### ☁️ Server Tasks

- [x] Update `server/index.js` process a new guest
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to create a Guest List
- [x] Update component to render to look like the wireframe
- [x] Create a Back button that can go back to menu page

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
