### ISSUE TITLE
Feature 5: User can manage Budget

### ISSUE THREAD

**Issue by michael5522** [michael5522/wedding-planner#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to both add item and cost, and view total budget and items added.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to add an item and input the cost and then view it.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-10-13 at 8 53 40 PM](https://user-images.githubusercontent.com/55678486/195758707-806f912c-9356-4ba2-8abd-650e14a34594.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to  add item, and cost

### ☁️ Server Tasks

- [x] Update `server/index.js` to process the item and cost
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to show the total budget, and cost of each item
- [x] Create a component that lets user to go back in the nav bar

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
