### ISSUE TITLE
Feature 4: User can view FAQ page

### ISSUE THREAD

**Issue by michael5522** [michael5522/wedding-planner#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view FAQ & go back.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view FAQ

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-10-13 at 8 55 27 PM](https://user-images.githubusercontent.com/55678486/195758906-65522b78-b4bd-4811-a96d-3968f3c5b628.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to render the FAQ page
- [x] Update component to generate the content for the FAQ
- [x] Allow User to click the back button to render the menu page

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
