### ISSUE TITLE
Feature 8: User can manage Food List

### ISSUE THREAD

**Issue by michael5522** [michael5522/wedding-planner#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add to Food List, and add category.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can see their organized list of foods by category. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-10-13 at 8 56 40 PM](https://user-images.githubusercontent.com/55678486/195759047-3605527b-e449-41a7-9b35-58c348f53bfa.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to process adding an item to the list, with category

### ☁️ Server Tasks

- [x] Update `server/index.js` to add an item to the list
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render the food List like the wireframe
- [x] Allow user to click on Go back to return to menu 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
