### ISSUE TITLE
Feature 1: User can view home page

### ISSUE THREAD

**Issue by michael5522** [michael5522/wedding-planner#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view home page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can log in or sign up

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-10-13 at 9 02 36 PM](https://user-images.githubusercontent.com/55678486/195759761-80af917d-63a3-4506-a17b-2fcd75979518.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to render the home page
- [x]  render  to look like wireframe
- [x] Update component to change page depending on if login or register is clicked
- [x]  User can click on login to go to login page
- [x] User can click on register to register a new account

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
