### ISSUE TITLE
Feature 2: User can login/Register

### ISSUE THREAD

**Issue by michael5522** [michael5522/wedding-planner#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can login or register

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to input their data to proceed
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-10-13 at 9 04 59 PM](https://user-images.githubusercontent.com/55678486/195760044-a85edf35-6ad2-4d3d-8346-9fc584673afe.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] User can login with email and password
- [x] User can create a new account with name,last name, email, password

### ☁️ Server Tasks

- [x] Update `server/index.js` to to check if account exists, if exist login, if not ask to create account
- [x] If it doesn't exist, create a new account in `server/index.js`
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to get to login
- [x] Or render a registration 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
