### ISSUE TITLE
Feature 3: User can view Menu Page 

### ISSUE THREAD

**Issue by michael5522** [michael5522/wedding-planner#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can get into the main menu page, where they can select any of the options to choose 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to get into Guest List Manager, Wedding Checklist, Budgeter, FAQ or the catering List

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-10-17 at 5 29 44 PM](https://user-images.githubusercontent.com/55678486/196307905-b86e74d4-76c3-4a5f-b98b-d2a3ff393834.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a Menu component 
- [x] render elements to look like wireframe
- [x] Update component to change location depending on where user clicked to #url.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
